# Generated by Django 5.1.4 on 2025-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_actors_remove_review_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='actors',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='review',
            name='director',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='review',
            name='running_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
